import Head from "next/head";
import { Container } from "../styles/ContainerElement";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Hola</h1>
      </Container>
    </div>
  );
}
